name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    container: 
        image: ghcr.io/trevorbakker-uta/cse3320:latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
